name: local-capgemini-blog

services:
  jekyll:
    image: jekyll/jekyll
    container_name: jekyll
    volumes:
      - .:/srv/jekyll
      - jekyll_gems:/usr/local/bundle
    ports:
      - "4000:4000"
    command: >
      sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --force_polling --drafts --future"

volumes:
  jekyll_gems:
